### ISSUE TITLE
Unable to run the command huetui from terminal

### ISSUE THREAD

**Issue by tomasbaran** [channel-42/hue-tui#1]
Hey there,

I was able to install huetui without any errors but once I run it, it throws this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/huetui", line 8, in <module>
    from hue_snek_pkg.hue_snek import Hue, Light
  File "/usr/local/lib/python3.7/site-packages/hue_snek_pkg/hue_snek.py", line 11, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

using python3 command and pip3 command in terminal (instead of python/pip, since I'm on macOs Catalina):
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by channel-42** [comment]
Hi,
it looks like python is not finding urllib3. Check if you have it installed by running `pip install urllib3`. If it continues to throw the same error, make sure that the pip package directory is in your $PATH. 

I'll add this dependency in an update to hue-snek today.

**Comment by tomasbaran** [comment]
Cool. Installing urllib3 solved it. Thanks! :)
